# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to NPM

on:
  push:
    branches:
      - master

permissions:
  id-token: 'write'
  contents: 'read'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Need at least 2 commits to compare versions

      - name: Check if package version changed
        id: version-updated
        run: node .github/scripts/check-version-change.cjs

      - uses: actions/setup-node@v4
        if: steps.version-updated.outputs.has-updated == 'true'
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install
        run: npm ci --ignore-scripts
        if: steps.version-updated.outputs.has-updated == 'true'

      - run: npm run clean
        if: steps.version-updated.outputs.has-updated == 'true'

      - run: npm run build
        if: steps.version-updated.outputs.has-updated == 'true'

      - run: npm publish --ignore-scripts
        if: steps.version-updated.outputs.has-updated == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
